### ISSUE TITLE
`drpcli gohai` panic on intel NUC

### ISSUE THREAD

**Issue by benagricola** [digitalrebar/provision#1064]
Filing here for visibility, but this is likely an issue with `godmi` itself or @VictorLowther's fork.

When running `drpcli gohai`, the following panic is seen:

```
[root@d94-c6-91-a6-f9-58 ~]# drpcli gohai
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1(0xc420197ad8)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:290 +0x13e
panic(0x991180, 0xdb70f0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
encoding/json.textMarshalerEncoder(0xc4200dd4a0, 0x990940, 0xc4202d05f1, 0x188, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:478 +0x95
encoding/json.(*structEncoder).encode(0xc4202cddd0, 0xc4200dd4a0, 0xa24740, 0xc4202d05a0, 0x199, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:639 +0x255
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200dd4a0, 0xa24740, 0xc4202d05a0, 0x199, 0xc4202d0100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:653 +0x64
encoding/json.(*ptrEncoder).encode(0xc420098b38, 0xc4200dd4a0, 0x97f040, 0xc4200987a0, 0x196, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:780 +0xe3
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200dd4a0, 0x97f040, 0xc4200987a0, 0x196, 0x970100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:785 +0x64
encoding/json.(*arrayEncoder).encode(0xc420098b40, 0xc4200dd4a0, 0x9485e0, 0xc4202d6218, 0x197, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:761 +0xdc
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc4200dd4a0, 0x9485e0, 0xc4202d6218, 0x197, 0xc4200d0100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:768 +0x64
encoding/json.(*sliceEncoder).encode(0xc420098b48, 0xc4200dd4a0, 0x9485e0, 0xc4202d6218, 0x197, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:735 +0xc1
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc4200dd4a0, 0x9485e0, 0xc4202d6218, 0x197, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:747 +0x64
encoding/json.(*structEncoder).encode(0xc4202cdcb0, 0xc4200dd4a0, 0x9d8340, 0xc4202d6208, 0x199, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:639 +0x255
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200dd4a0, 0x9d8340, 0xc4202d6208, 0x199, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:653 +0x64
encoding/json.(*structEncoder).encode(0xc4202cd7d0, 0xc4200dd4a0, 0x9e16a0, 0xc4202d61e0, 0x199, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:639 +0x255
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200dd4a0, 0x9e16a0, 0xc4202d61e0, 0x199, 0xc4202d0100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:653 +0x64
encoding/json.(*ptrEncoder).encode(0xc420098ca0, 0xc4200dd4a0, 0x980720, 0xc4202d61e0, 0x16, 0x980100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:780 +0xe3
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200dd4a0, 0x980720, 0xc4202d61e0, 0x16, 0xc4202d0100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:785 +0x64
encoding/json.(*encodeState).reflectValue(0xc4200dd4a0, 0x980720, 0xc4202d61e0, 0x16, 0xc4202d0100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:325 +0x82
encoding/json.interfaceEncoder(0xc4200dd4a0, 0x9984e0, 0xc4202ec250, 0x94, 0xc4202e0100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:611 +0xdb
encoding/json.(*mapEncoder).encode(0xc4200988b8, 0xc4200dd4a0, 0x98b8e0, 0xc4202cc3f0, 0x15, 0x980100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:684 +0x45f
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4200dd4a0, 0x98b8e0, 0xc4202cc3f0, 0x15, 0xc4202c0100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:700 +0x64
encoding/json.(*encodeState).reflectValue(0xc4200dd4a0, 0x98b8e0, 0xc4202cc3f0, 0x15, 0x100)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:325 +0x82
encoding/json.(*encodeState).marshal(0xc4200dd4a0, 0x98b8e0, 0xc4202cc3f0, 0x100, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:298 +0xa5
encoding/json.Marshal(0x98b8e0, 0xc4202cc3f0, 0xc420197b40, 0x410958, 0x10, 0x97ab80, 0xc420098801)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:161 +0x5f
github.com/digitalrebar/provision/vendor/github.com/VictorLowther/jsonpatch2/utils.Remarshal(0x98b8e0, 0xc4202cc3f0, 0x93e740, 0xc4202ec140, 0x37, 0x0)
	/home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/VictorLowther/jsonpatch2/utils/utils.go:73 +0x76
github.com/digitalrebar/provision/cli.prettyPrintBuf(0x98b8e0, 0xc4202cc3f0, 0xc420197c40, 0xa08df8e5, 0xdd6147924c037c7b, 0xc42032a000, 0xdd00000000001000)
	/home/travis/gopath/src/github.com/digitalrebar/provision/cli/utils.go:155 +0x64
github.com/digitalrebar/provision/cli.prettyPrint(0x98b8e0, 0xc4202cc3f0, 0xa3837a, 0x7)
	/home/travis/gopath/src/github.com/digitalrebar/provision/cli/utils.go:166 +0x4e
github.com/digitalrebar/provision/cli.gohai(0x0, 0x0)
	/home/travis/gopath/src/github.com/digitalrebar/provision/cli/gohai_linux.go:40 +0x444
github.com/digitalrebar/provision/cli.NewApp.func3(0xc4202d8000, 0xde60c0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/digitalrebar/provision/cli/startup.go:194 +0x22
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202d8000, 0xde60c0, 0x0, 0x0, 0xc4202d8000, 0xde60c0)
	/home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201dac80, 0x0, 0xc4200bca00, 0x4)
	/home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201dac80, 0xc420197f78, 0xc420086058)
	/home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/travis/gopath/src/github.com/digitalrebar/provision/cmds/drpcli/drpcli.go:10 +0x27
```

I've gone down the rabbit hole to find out where and it appears that the `Upgrade` field as reported by the processor is 'Out of Spec' according to `dmidecode`:

```
[root@d94-c6-91-a6-f9-58 ~]# dmidecode --type processor | grep Upgrade
	Upgrade: <OUT OF SPEC>
```

Printing the raw dmiInfo.Processors` field gives the following, with the paniced value:

```
Processors {2 2 4 [Processor Information
	Socket Designation: U3E1
	Processor Type: CentralProcessor
	Family: Core i3
	Manufacturer: Intel(R) Corporation
	ID: bfebfbff000806ea
	Version: Intel(R) Core(TM) i3-8109U CPU @ 3.00GHz
	Voltage: 0.8V
	External Clock: 100 MHz
	Max Speed: 3500 MHz
	Current Speed: 2300 MHz
	Status: CPU Enabled
	Upgrade: %!s(PANIC=runtime error: index out of range)
	L1 Cache Handle: 0x44
	L2 Cache Handle: 0x45
	L3 Cache Handle: 0x46
	Serial Number: To Be Filled By O.E.M.
	Asset Tag: To Be Filled By O.E.M.
	Part Number: To Be Filled By O.E.M.
	Core Count: 2
	Core Enabled: 2
	Thread Count: 4
	Characteristics: 64-bit Capable
		Multi-Core
		Hardware Thread
		Execute Protection
		Enhanced Virtualization
		Power/Performance Control
]}
```

`godmi` doesn't appear to handle nonexistent `Upgrade` flags so panics as whatever the processor is reporting for `data[0x19]` is not in the list of upgrades.

Unfortunately I don't know how to drag in a modified `godmi` via the gohai plugins (my go-fu is weak) to print the output from that var :(

**Comment by galthaus** [comment]
#1065 should hopefully address it.  I can't test it.  So, please pull tip and close this if it works.

Thanks for the notes!

**Comment by benagricola** [comment]
```
[root@nuc2 ~]# ./drpcli gohai | jq '.DMI.Processors'.Items[].Upgrade
"Unknown_Upgrade_Value_60"
```

`0x3C` (60) was added in SMBIOS Spec 3.2.0 along with some others, doesn't look like it's made its way into `dmidecode` either. 

But yes this fixes it, thanks @galthaus
