### ISSUE TITLE
gohai parsing problem prevents discover from completing

### ISSUE THREAD

**Issue by brunnels** [digitalrebar/provision#1118]
Here's dmidecode output:

[dmidecode.txt](https://github.com/digitalrebar/provision/files/2948680/dmidecode.txt)

Error message:
```
[root@node3 ~]# drpcli gohai --debug
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1(0xc42016dad8)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:290 +0x13e
panic(0x9996e0, 0xdc4150)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
github.com/digitalrebar/provision/vendor/github.com/VictorLowther/godmi.ProcessorVoltage.String(0x104, 0x7fc1dd5eed48, 0xc420364710)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/VictorLowther/godmi/type4_processor.go:580 +0x17d
github.com/digitalrebar/provision/vendor/github.com/VictorLowther/godmi.ProcessorVoltage.MarshalText(0x99f504, 0x998f00, 0x100, 0x7fc1dd5eed48, 0x998f00, 0xc42036
4710)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/VictorLowther/godmi/type4_processor.go:586 +0x2a
encoding/json.textMarshalerEncoder(0xc4200b8fd0, 0x998f00, 0xc4202aa048, 0x188, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:478 +0x95
encoding/json.(*structEncoder).encode(0xc42035c630, 0xc4200b8fd0, 0xa2be80, 0xc4202aa000, 0x199, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:639 +0x255
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200b8fd0, 0xa2be80, 0xc4202aa000, 0x199, 0xc4202a0100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:653 +0x64
encoding/json.(*ptrEncoder).encode(0xc42000cbb0, 0xc4200b8fd0, 0x9874e0, 0xc42000c798, 0x196, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:780 +0xe3
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200b8fd0, 0x9874e0, 0xc42000c798, 0x196, 0x980100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:785 +0x64
encoding/json.(*arrayEncoder).encode(0xc42000cbb8, 0xc4200b8fd0, 0x9508e0, 0xc42028f398, 0x197, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:761 +0xdc
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc4200b8fd0, 0x9508e0, 0xc42028f398, 0x197, 0xc4200b0100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:768 +0x64
encoding/json.(*sliceEncoder).encode(0xc42000cbc0, 0xc4200b8fd0, 0x9508e0, 0xc42028f398, 0x197, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:735 +0xc1
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc4200b8fd0, 0x9508e0, 0xc42028f398, 0x197, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:747 +0x64
encoding/json.(*structEncoder).encode(0xc42035c510, 0xc4200b8fd0, 0x9e0c60, 0xc42028f388, 0x199, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:639 +0x255
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200b8fd0, 0x9e0c60, 0xc42028f388, 0x199, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:653 +0x64
encoding/json.(*structEncoder).encode(0xc42035c030, 0xc4200b8fd0, 0x9ea180, 0xc42028f360, 0x199, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:639 +0x255
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200b8fd0, 0x9ea180, 0xc42028f360, 0x199, 0xc420280100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:653 +0x64
encoding/json.(*ptrEncoder).encode(0xc42000cd18, 0xc4200b8fd0, 0x988bc0, 0xc42028f360, 0x16, 0x980100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:780 +0xe3
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4200b8fd0, 0x988bc0, 0xc42028f360, 0x16, 0xc420280100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:785 +0x64
encoding/json.(*encodeState).reflectValue(0xc4200b8fd0, 0x988bc0, 0xc42028f360, 0x16, 0xc420280100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:325 +0x82
encoding/json.interfaceEncoder(0xc4200b8fd0, 0x9a0c20, 0xc4202b67a0, 0x94, 0xc4202b0100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:611 +0xdb
encoding/json.(*mapEncoder).encode(0xc42000c930, 0xc4200b8fd0, 0x993e40, 0xc420290660, 0x15, 0x990100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:684 +0x45f
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4200b8fd0, 0x993e40, 0xc420290660, 0x15, 0xc420290100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:700 +0x64
encoding/json.(*encodeState).reflectValue(0xc4200b8fd0, 0x993e40, 0xc420290660, 0x15, 0x100)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:325 +0x82
encoding/json.(*encodeState).marshal(0xc4200b8fd0, 0x993e40, 0xc420290660, 0x100, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:298 +0xa5
encoding/json.Marshal(0x993e40, 0xc420290660, 0xc42016db40, 0x410958, 0x10, 0x9830e0, 0x1)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/encoding/json/encode.go:161 +0x5f
github.com/digitalrebar/provision/vendor/github.com/VictorLowther/jsonpatch2/utils.Remarshal(0x993e40, 0xc420290660, 0x946a40, 0xc4202b6690, 0x37, 0x0)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/VictorLowther/jsonpatch2/utils/utils.go:73 +0x76
github.com/digitalrebar/provision/cli.prettyPrintBuf(0x993e40, 0xc420290660, 0xc42016dc40, 0xa8156357, 0x716063fadf654208, 0xc420301000, 0x7100000000001000)
        /home/travis/gopath/src/github.com/digitalrebar/provision/cli/utils.go:238 +0x64
github.com/digitalrebar/provision/cli.prettyPrint(0x993e40, 0xc420290660, 0xa41617, 0x7)
        /home/travis/gopath/src/github.com/digitalrebar/provision/cli/utils.go:249 +0x4e
github.com/digitalrebar/provision/cli.gohai(0x0, 0x0)
        /home/travis/gopath/src/github.com/digitalrebar/provision/cli/gohai_linux.go:40 +0x444
github.com/digitalrebar/provision/cli.NewApp.func3(0xc4202a2780, 0xc420277960, 0x0, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/digitalrebar/provision/cli/startup.go:241 +0x22
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202a2780, 0xc420277930, 0x1, 0x1, 0xc4202a2780, 0xc420277930)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201b2f00, 0x0, 0xc420066ac0, 0x4)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201b2f00, 0xc42016df78, 0xc420074058)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/travis/gopath/src/github.com/digitalrebar/provision/cmds/drpcli/drpcli.go:10 +0x27
```

**Comment by VictorLowther** [comment]
Addressed by https://github.com/digitalrebar/provision/pull/1149 and others
