### ISSUE TITLE
Ansible dynamic inventory fails with "ValueError: No JSON object could be decoded"

### ISSUE THREAD

**Issue by talarczykco** [digitalrebar/provision#1181]
On Friday, I had `integrations/ansible/inventory.py` working with correct `RS_PROFILE`, `RS_ENDPOINT`, and `RS_KEY` values. Today, the script errors with:

```
Traceback (most recent call last):
  File "./inventory.py", line 128, in <module>
    main()
  File "./inventory.py", line 61, in main
    params = profile_raw.json()
  File "/Users/michael/.local/share/virtualenvs/ops-ansible-drp-LXiQCs9R/lib/python2.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Inserting a `print(profile_raw.content)` at line 61 emits HTML instead of the expected JSON. Has anything changed with the DRP endpoint serving this data?

Steps to reproduce:
```
curl -O https://raw.githubusercontent.com/digitalrebar/provision/master/integrations/ansible/inventory.py
chmod a+x inventory.py
export RS_ENDPOINT=https://172.xx.xx.xx:8092
export RS_KEY=<ITSASECRET>
export RS_PROFILE=ansible-kubespray
./inventory.py
```

**Comment by zehicle** [comment]
The script is self-contained to your local endpoint.  If this was working and then stopped, then something in your system changed.  Check `drpcli profiles ansible-kubespray params` and see what it returns.  I suspect there's something in that profile that is not rendering correctly.

**Comment by talarczykco** [comment]
my actual endpoint is `https://portal.rackn.io/#/e/172.22.1.188:8092` which I think is the hosted portal.

I'll figure out how to set up `drpcli` but according the the web interface, my profile hasn't changed. The endpoint just appears to emit HTML instead of JSON now.

**Comment by sygibson** [comment]
@talarczykco 

Your Endpoint is your DRP instance via direct HTTP URL - not via the Portal - so you should have:
`export RS_ENDPOINT=https://10.10.10.10:8092`
putting the Portal URL in the RS_ENDPOINT nets the same error message that you showed.

When I set RS_ENDPOINT to the Portal URL, like:
`export RS_ENDPOINT=https://portal.rackn.io/#/e/10.10.10.10:8092`

I also get the same python barf:

```[root@kvm-0 ~]# RS_PROFILE=mycluster ./inventory.py  | jq '.'
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./inventory.py", line 128, in <module>
    main()
  File "./inventory.py", line 61, in main
    params = profile_raw.json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 802, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded```

Please test with the correct RS_ENDPOINT reference, and let us know how that works for you.

**Comment by talarczykco** [comment]
Shortening `RS_ENDPOINT` to the direct server port worked for me - thanks for the assist!
