### ISSUE TITLE
drpcli panic when using exit_reboot

### ISSUE THREAD

**Issue by benagricola** [digitalrebar/provision#1253]
cc @VictorLowther 

Reported this in slack just now

Running on a cumulus linux switch (3.6.1).

```
root@cumulus:~#  /usr/local/bin/drpcli version
Version: v3.13.6-tip-36-7b40568b7f2a2d6fa8da0ab96360732f25abaf26
```

My task has the following meta definition:

```yaml
Meta:
  color: red
  feature-flags: sane-exit-codes
  icon: linux
  title: Install Cumulus Linux
```

The relevant part of the task itself is this:

```bash
    echo "Configuring Onie installer with image ${IMAGE}"
    /usr/cumulus/bin/onie-install -fa -i ${IMAGE}

    # Unset request-install so this doesn't loop
    drpcli machines set ${RS_UUID} param cumulus/install-state to 'installed' || \
      echo "Request-install param not set on machine, so could not be removed. Likely enforced redeploy by stage profile.."

    exit_reboot
```

This causes `drpcli` to exit when the reboot code is seen, and the following panic is reported. The reboot does not happen.

I've had successful reboots using this same task on other cumulus linux switches (although likely older `drpcli` versions).

```
Task signalled that it finished normally
Agent rebooting
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x843a56]

goroutine 1 [running]:
github.com/digitalrebar/provision/models.(*Info).HasFeature(0x0, 0xae4fa5, 0x10, 0x0)
        /home/travis/gopath/src/github.com/digitalrebar/provision/models/info.go:63 +0x26
github.com/digitalrebar/provision/api.(*MachineAgent).power(0xc000316000, 0xaded5e, 0x6, 0x10, 0x0)
        /home/travis/gopath/src/github.com/digitalrebar/provision/api/agent.go:140 +0x67
github.com/digitalrebar/provision/api.(*MachineAgent).Run(0xc000316000, 0xc00028a000, 0xc000010000)
        /home/travis/gopath/src/github.com/digitalrebar/provision/api/agent.go:661 +0x5be
github.com/digitalrebar/provision/cli.registerMachine.func21(0xc000236a00, 0xc000255bf0, 0x1, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/digitalrebar/provision/cli/machines.go:323 +0x144
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).execute(0xc000236a00, 0xc000255bc0, 0x1, 0x1, 0xc000236a00, 0xc000255bc0)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000188f00, 0x997f0e, 0xc000163f88, 0xc000082058)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:852 +0x2c0
github.com/digitalrebar/provision/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/digitalrebar/provision/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /home/travis/gopath/src/github.com/digitalrebar/provision/cmds/drpcli/drpcli.go:10 +0x28
```

**Comment by benagricola** [comment]
Pretty sure this was fixed a couple of days after by greg but I didn't update tip. Will confirm now and close if so.

**Comment by benagricola** [comment]
Confirmed that this is fixed in the latest tip, apologies for the issue spam :)
