### ISSUE TITLE
Potential race condition in Event System

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/provision#578]
The deregister and the event processing loop can race on a closed channel.  This is not fatal, but can cause DATA Race failures in unit tests.

This is at line 152 in event_stream.go (is part of the problem).

data
----
dr-provision2017/12/03 06:03:32.915844 Version: v3.0.2-pre-alpha-NotSet
dr-provision2017/12/03 06:03:32.916187 Extracting Default Assets
dr-provision2017/12/03 06:03:50.678048 Starting TFTP server
dr-provision2017/12/03 06:03:50.678625 Starting static file server
dr-provision2017/12/03 06:03:50.679695 Starting API server
==================
WARNING: DATA RACE
Write at 0x00c420390000 by goroutine 25:
  runtime.closechan()
      /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/chan.go:313 +0x0
  github.com/digitalrebar/provision/api.(*EventStream).Deregister()
      github.com/digitalrebar/provision/api/_test/_obj_test/event_stream.go:330 +0x807
  github.com/digitalrebar/provision/api.(*EventStream).WaitFor()
      github.com/digitalrebar/provision/api/_test/_obj_test/event_stream.go:376 +0xad8
  github.com/digitalrebar/provision/api.(*Client).Agent()
      github.com/digitalrebar/provision/api/_test/_obj_test/jobs.go:596 +0xa8f
  github.com/digitalrebar/provision/api.runAgent()
      /home/travis/gopath/src/github.com/digitalrebar/provision/api/jobs_test.go:31 +0x153
  github.com/digitalrebar/provision/api.TestChangeStage()
      /home/travis/gopath/src/github.com/digitalrebar/provision/api/change_stage_test.go:288 +0x2983
  testing.tRunner()
      /home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:746 +0x16c
Previous read at 0x00c420390000 by goroutine 36:
  runtime.chansend()
      /home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/chan.go:128 +0x0
  github.com/digitalrebar/provision/api.(*EventStream).processEvents.func1()
      github.com/digitalrebar/provision/api/_test/_obj_test/event_stream.go:198 +0x15e
Goroutine 25 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.9.linux.amd64/src/testing/testing.go:921 +0x206
  github.com/digitalrebar/provision/api.TestMain()
      /home/travis/gopath/src/github.com/digitalrebar/provision/api/common_test.go:227 +0x72f
  main.main()
      github.com/digitalrebar/provision/api/_test/_testmain.go:416 +0x2f3
Goroutine 36 (running) created at:
  github.com/digitalrebar/provision/api.(*EventStream).processEvents()
      github.com/digitalrebar/provision/api/_test/_obj_test/event_stream.go:194 +0x3fe
==================
panic: send on closed channel
goroutine 545 [running]:
github.com/digitalrebar/provision/api.(*EventStream).processEvents.func1(0xc420552d50, 0x320958fd, 0xed1b58ad9, 0x0, 0xc420413188, 0x8, 0xc4204131a0, 0x6, 0xc42027a180, 0x24, ...)
        github.com/digitalrebar/provision/api/_test/_obj_test/event_stream.go:198 +0x15f
created by github.com/digitalrebar/provision/api.(*EventStream).processEvents
        github.com/digitalrebar/provision/api/_test/_obj_test/event_stream.go:194 +0x3ff

**Comment by galthaus** [comment]
Resolved by the set of pull requests two weeks ago.
