### ISSUE TITLE
Version: v4.1.1 Panics.

### ISSUE THREAD

**Issue by preachermanx** [digitalrebar/provision#93]
Experiencing this in normal operation. Three times in three days now.

With a total of only 6 hosts booting.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbcec3c]

goroutine 2115660 [running]:
github.com/rackn/provision-server/v4/backend.(*Machine).validate(0xc00827c2d0, 0xc00a9f42c0)
        /home/travis/gopath/src/github.com/rackn/provision-server/backend/machines.go:609 +0xedc
github.com/rackn/provision-server/v4/backend.(*Machine).beforeSave(0xc00827c2d0, 0xc00a9f42c0, 0xc00827c2d0, 0x7f688a95b270)
        /home/travis/gopath/src/github.com/rackn/provision-server/backend/machines.go:672 +0xb0
github.com/rackn/provision-server/v4/backend.(*RequestTracker).save(0xc00a9f42c0, 0x11a1da0, 0xc00827c2d0, 0x11a1da0, 0xc00827c2d0, 0xc002ff6f01)
        /home/travis/gopath/src/github.com/rackn/provision-server/backend/requestTracker.go:438 +0x1aa
github.com/rackn/provision-server/v4/backend.(*RequestTracker).Save(0xc00a9f42c0, 0x11a1da0, 0xc00827c2d0, 0xc00099ff00, 0x0, 0x0)
        /home/travis/gopath/src/github.com/rackn/provision-server/backend/requestTracker.go:475 +0x42d
github.com/rackn/provision-server/v4/midlayer.(*DhcpRequest).checkMachine.func1(0xc0042bad80)
        /home/travis/gopath/src/github.com/rackn/provision-server/midlayer/dhcp.go:314 +0xb5f
github.com/rackn/provision-server/v4/backend.(*RequestTracker).Do(0xc00a9f42c0, 0xc009e1f8b0)
        /home/travis/gopath/src/github.com/rackn/provision-server/backend/requestTracker.go:362 +0x1f4
github.com/rackn/provision-server/v4/midlayer.(*DhcpRequest).checkMachine(0xc0006823c0, 0xc0097e5570)
        /home/travis/gopath/src/github.com/rackn/provision-server/midlayer/dhcp.go:241 +0x328
github.com/rackn/provision-server/v4/midlayer.(*DhcpRequest).coalesceOptions(0xc0006823c0, 0xc0097e5570)
        /home/travis/gopath/src/github.com/rackn/provision-server/midlayer/dhcp.go:348 +0x498
github.com/rackn/provision-server/v4/midlayer.(*DhcpRequest).buildDhcpOptions(...)
        /home/travis/gopath/src/github.com/rackn/provision-server/midlayer/dhcp.go:443
github.com/rackn/provision-server/v4/midlayer.(*DhcpRequest).ServeDHCP(0xc0006823c0, 0xc009e91ce0, 0x4)
        /home/travis/gopath/src/github.com/rackn/provision-server/midlayer/dhcp.go:708 +0xdba
github.com/rackn/provision-server/v4/midlayer.(*DhcpRequest).Process(0xc0006823c0, 0x7a8744, 0xc00017a7a8, 0x6e148b, 0x3e98e80)
        /home/travis/gopath/src/github.com/rackn/provision-server/midlayer/dhcp.go:791 +0x433
github.com/rackn/provision-server/v4/midlayer.(*DhcpRequest).Run(0xc0006823c0, 0x224)
        /home/travis/gopath/src/github.com/rackn/provision-server/midlayer/dhcp.go:816 +0x40
created by github.com/rackn/provision-server/v4/midlayer.(*DhcpHandler).Serve
        /home/travis/gopath/src/github.com/rackn/provision-server/midlayer/dhcp.go:888 +0x340

```

**Comment by preachermanx** [comment]
Continuing to occur.

Also on panic it is not cleaning up the plugins?  

```4 S root      7070     1  0  80   0 - 29040 -      06:16 pts/1    00:00:00 /root/drp/drp-data/plugins/raid listen /var/run/raid.toPlugin.2 /var/run/raid.fromPlugin.2
4 S root      7077     1  0  80   0 - 28434 -      06:16 pts/1    00:00:00 /root/drp/drp-data/plugins/ux-views listen /var/run/ux-views.toPlugin.3 /var/run/ux-views.fromPlugin.3
4 S root      7083     1  0  80   0 - 29124 -      06:16 pts/1    00:00:00 /root/drp/drp-data/plugins/image-deploy listen /var/run/image-deploy.toPlugin.4 /var/run/image-deploy.fromPlugin.4
4 S root      7087     1  0  80   0 - 28934 -      06:16 pts/1    00:00:00 /root/drp/drp-data/plugins/ipmi listen /var/run/ipmi.toPlugin.5 /var/run/ipmi.fromPlugin.5
4 S root      7105     1  0  80   0 - 28983 -      06:16 pts/1    00:00:00 /root/drp/drp-data/plugins/pool listen /var/run/pool.toPlugin.6 /var/run/pool.fromPlugin.6
4 S root      7607     1  0  80   0 - 28688 -      Oct18 pts/1    00:00:00 /root/drp/drp-data/plugins/raid listen /var/run/raid.toPlugin.6 /var/run/raid.fromPlugin.6
4 S root     15173     1  0  80   0 - 28434 -      Oct17 pts/1    00:00:00 /root/drp/drp-data/plugins/ux-views listen /var/run/ux-views.toPlugin.3 /var/run/ux-views.fromPlugin.3
4 S root     15178     1  0  80   0 - 29476 -      Oct17 pts/1    00:00:00 /root/drp/drp-data/plugins/image-deploy listen /var/run/image-deploy.toPlugin.4 /var/run/image-deploy.fromPlugin.4
4 S root     15183     1  0  80   0 - 28934 -      Oct17 pts/1    00:00:07 /root/drp/drp-data/plugins/ipmi listen /var/run/ipmi.toPlugin.5 /var/run/ipmi.fromPlugin.5
4 S root     18497     1  0  80   0 - 28786 -      Oct18 pts/1    00:00:00 /root/drp/drp-data/plugins/ux-views listen /var/run/ux-views.toPlugin.2 /var/run/ux-views.fromPlugin.2
4 S root     18502     1  0  80   0 - 29124 -      Oct18 pts/1    00:00:00 /root/drp/drp-data/plugins/image-deploy listen /var/run/image-deploy.toPlugin.3 /var/run/image-deploy.fromPlugin.3
4 S root     18506     1  0  80   0 - 28582 do_epo Oct18 pts/1    00:00:05 /root/drp/drp-data/plugins/ipmi listen /var/run/ipmi.toPlugin.4 /var/run/ipmi.fromPlugin.4
4 S root     48739     1  0  80   0 - 29124 -      Oct18 pts/1    00:00:00 /root/drp/drp-data/plugins/image-deploy listen /var/run/image-deploy.toPlugin.2 /var/run/image-deploy.fromPlugin.2
4 S root     48744     1  0  80   0 - 28934 -      Oct18 pts/1    00:00:04 /root/drp/drp-data/plugins/ipmi listen /var/run/ipmi.toPlugin.3 /var/run/ipmi.fromPlugin.3
4 S root     48752     1  0  80   0 - 28434 -      Oct18 pts/1    00:00:00 /root/drp/drp-data/plugins/ux-views listen /var/run/ux-views.toPlugin.4 /var/run/ux-views.fromPlugin.4
4 S root     48764     1  0  80   0 - 29863 -      Oct18 pts/1    00:01:12 /root/drp/drp-data/plugins/pool listen /var/run/pool.toPlugin.5 /var/run/pool.fromPlugin.5
```

**Comment by preachermanx** [comment]
v4.1.2 seems to have resoved.
